In [1]:
import numpy as np
edges=[[1,2,4],[1,3,6],[2,3,5],[3,4,2]]
edges=np.array(edges)
print(edges)

[[1 2 4]
 [1 3 6]
 [2 3 5]
 [3 4 2]]


In [2]:
def Min(candidate):
    MinInList=candidate[0]
    
    for so in candidate:
           if MinInList[1]>=so[1]:
                MinInList=so
    return MinInList


In [ ]:
def Min(candidate):
    MinInList=candidate[0]
    
    for so in candidate:
           if MinInList[1]>so[1]:
                MinInList=so
    return MinInList

# Complete the shortestReach function below.
def shortestReach(N, edges, S):
    Graph=[]
    for i in range(N):
        Graph.append([])
    for edge in edges:
       Graph[edge[0]-1].append([edge[1],edge[2]])
       Graph[edge[1]-1].append([edge[0],edge[2]])
    
    Tree=[]
    for k in range(N):
        Tree.append(-1)
    
    candidate=[]
## first step: add start node into the candidate list
    candidate.append([S,0])
## loop: add min distance link into Tree list
    while len(candidate) !=0:
        print(candidate)
        FindMin=Min(candidate)
       ##find min cost
        Tree[FindMin[0]-1]=FindMin[1]
        candidate.remove(FindMin)
        ##add link into candidate list sao cho chua xuat hien tong Tree list
        
        PrevNode=FindMin
       
        NextPath=Graph[PrevNode[0]-1]
        
        for node  in NextPath:### check in Graph
                        
                        ##if next node in tree list, then ignore that node
                      
                        if Tree[node[0]-1]==-1:
                                   Willbeadd=[node[0],node[1]+PrevNode[1]]
                                   candidate.append(Willbeadd)
    Tree.pop(S-1)                           
    return Tree