In [649]:
import numpy as np
def Init_Gene():
    gene = np.array([1,2,3,4,5,6,7,8,9]);
    np.random.shuffle(gene)
    return gene
def Init_Board():
    b = np.zeros((9,9)).astype(int)
    for i in range(9):
        b[i] = Init_Gene()
    return b

def Init_Quanthe(SizePop):
    Pop = []
    for i in range(SizePop):
        Pop.append(Init_Board())
    return Pop

In [650]:
def fitness_function(cathe):
    temp=cathe.T
    count_c=0
    count_grid=0
    count_db=0
    for i in range(9):
        for j in range(1,10):
            c=np.sum(temp[i]==j)
            if c>=2:
                count_c=count_c+c-1
    for i in range(3):
        for j in range(3):
            grid=cathe[i*3:i*3+3,j*3:j*3+3].reshape(9)
            for k in range(1,10):
                g=np.sum(grid==k)
                if g>=2:
                    count_grid=count_grid+g-1
    count=[1,4,7]
    taphop=[]
    for i in count:
        for j in count:
            taphop.append(cathe[i][j])
    for i in range(10):
        tem=taphop.count(i)
        if tem>=2:
            count_db=count_db+tem-1
        
    return count_c+count_grid+count_db
        

In [657]:
def select2(cathe):
    count=[1,4,7]
    taphop=[]
    count_db=0
    for i in count:
        for j in count:
            taphop.append(cathe[i][j])
    for i in range(10):
        tem=taphop.count(i)
        if tem>=2:
            count_db=count_db+tem-1
    return count_db

In [651]:
def selection(Quanthe_value,soluongcathe):
    ids=np.argsort(Quanthe_value)
    return ids[0:soluongcathe]

In [652]:
##tao ngau nhien nhiu cap bo me
def set_bome(soluongcathetot,socapbome):
    Bome=[]
    for i in range(socapbome*100):
        z=np.random.randint(0,soluongcathetot,2).astype(int)
        if z[1]!=z[0]:
            if len(Bome)!=socapbome:
                Bome.append(z)
            else:   
                break
    return Bome
    

In [653]:
## lai tao uniform
def Crossover(cathe1,cathe2):
    ###parent la mot mang 2 chieu
    ###trao doi cac row cua cua 2 bo me
   
    chance = np.random.randint(7,10,1)
    
    if chance >7:
        ip_lai = np.random.randint(0,9,chance-5)
        N=len(id_lai)
        temp=np.zeros((N,9)).astype(int)
        temp=cathe1[id_lai]
        cathe1[id_lai]=cathe2[id_lai]
        cathe2[id_lai]=temp
    return cathe1, cathe2

In [654]:
def Mutation(DoiCon):
    
    chance = np.random.randint(2,10,1)
    if chance >7 :  
        rowid=np.random.randint(0,9,chance-7)
        for i in rowid:
                ids=np.random.randint(0,9,2)
                temp= DoiCon[i][ids[0]]
                DoiCon[i][ids[0]]=DoiCon[i][ids[1]]
                DoiCon[i][ids[1]]=temp
    return DoiCon

In [661]:
### init population
SizePop = 10000
soluongcathetot=1000#chi chon ra cac ca the tot nhat lam bo me
socapbome=2500 ##20cap bo me
Quanthe=Init_Quanthe(10000)##
#Quanthe = Quanthe*SizePop
Quanthe=np.array(Quanthe)
## tao ra id de lai ghep voi nhau
print(Quanthe[0])
Quanthexs=[]
for i in range(SizePop):
        dacbiet=select2(Quanthe[i])
        if dacbiet==0:
            Quanthexs.append(Quanthe[i])
print(len(Quanthexs))
     

[[4 9 7 1 8 5 2 6 3]
 [6 2 9 4 7 3 5 1 8]
 [7 8 2 3 4 6 1 5 9]
 [4 7 5 2 9 1 6 3 8]
 [7 9 6 5 4 1 2 8 3]
 [8 4 2 9 1 5 3 6 7]
 [8 7 9 6 2 1 3 5 4]
 [8 1 9 3 7 4 5 6 2]
 [5 4 1 8 7 9 6 2 3]]
31


In [656]:
epoch=1000
point = 100
generate = 1
for lap in range(epoch):
        giatrifit=[]
        Doicon=[]
        for i in range(Quanthe.shape[0]):## tinh fitness cho ca quan the
                giatrifit.append(fitness_function(Quanthe[i]))
        giatrifit=np.array(giatrifit)
        if point <= 10:
            generate = 2
        else:
            generate = 1
        id_cathe=selection(giatrifit,int(soluongcathetot/generate))## chon loc ca the tot
       
        
        Quanthemoi=Quanthe[id_cathe] ## quan the  sau khi chon loc
        
        Quanthemoi = list(Quanthemoi)*generate
        
        id_bome=set_bome(soluongcathetot,socapbome)
        point = min(giatrifit)
        print(" the he thu:",lap, "gia tri fit: ",point)
        if min(giatrifit) == 0:
            break
        for j in range(socapbome):
            f1,f2=Crossover(Quanthemoi[id_bome[j][0]],Quanthemoi[id_bome[j][1]])
            Quanthemoi.append(Mutation(f1))
            Quanthemoi.append(Mutation(f2))
        
        Quanthe = np.array(Quanthemoi)

 the he thu: 0 gia tri fit:  38
 the he thu: 1 gia tri fit:  35
 the he thu: 2 gia tri fit:  34
 the he thu: 3 gia tri fit:  33
 the he thu: 4 gia tri fit:  30
 the he thu: 5 gia tri fit:  29
 the he thu: 6 gia tri fit:  27
 the he thu: 7 gia tri fit:  27
 the he thu: 8 gia tri fit:  24
 the he thu: 9 gia tri fit:  24
 the he thu: 10 gia tri fit:  23
 the he thu: 11 gia tri fit:  22
 the he thu: 12 gia tri fit:  22
 the he thu: 13 gia tri fit:  20
 the he thu: 14 gia tri fit:  21
 the he thu: 15 gia tri fit:  20
 the he thu: 16 gia tri fit:  19
 the he thu: 17 gia tri fit:  18
 the he thu: 18 gia tri fit:  19
 the he thu: 19 gia tri fit:  18
 the he thu: 20 gia tri fit:  18
 the he thu: 21 gia tri fit:  18
 the he thu: 22 gia tri fit:  17
 the he thu: 23 gia tri fit:  16
 the he thu: 24 gia tri fit:  15
 the he thu: 25 gia tri fit:  15
 the he thu: 26 gia tri fit:  15
 the he thu: 27 gia tri fit:  15
 the he thu: 28 gia tri fit:  15
 the he thu: 29 gia tri fit:  14
 the he thu: 30 gia 

KeyboardInterrupt: 

In [ ]:
print(Quanthe[np.argmin(giatrifit)])
